org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
group=malte0811.ferritecore

# Common
minecraft_version=26.1
next_major_mc=27
# Updates: https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.1-1

# NeoForge: https://projects.neoforged.net/neoforged/neoforge
neo_version=26.1.0.1-beta
# Updates: https://projects.neoforged.net/neoforged/ModDevGradle
mdg_version=2.0.141

# Fabric
# Updates: https://fabricmc.net/versions.html
fabric_loader_version=0.18.4

# Mod options
mod_name=FerriteCore
mod_author=malte0811
mod_id=ferritecore
mod_version=8.2.0

# TODO can this be made to work?
#org.gradle.configuration-cache=true
