org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
group=malte0811.ferritecore

# Common
minecraft_version=1.21.9
next_major_mc=1.22
# https://parchmentmc.org/docs/getting-started
parchment_minecraft=1.21.8
parchment_version=2025.07.20
# Updates: https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.9-20250930.151910

# NeoForge: https://projects.neoforged.net/neoforged/neoforge
neo_version=21.9.9-beta
# Updates: https://projects.neoforged.net/neoforged/ModDevGradle
mdg_version=2.0.112

# Fabric
# Updates: https://fabricmc.net/versions.html
fabric_loader_version=0.17.2

# Mod options
mod_name=FerriteCore
mod_author=malte0811
mod_id=ferritecore
mod_version=8.0.2

# TODO can this be made to work?
#org.gradle.configuration-cache=true
