org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
group=malte0811.ferritecore

# Common
minecraft_version=1.21.4
next_major_mc=1.22
parchment_minecraft=1.21
parchment_version=2024.06.23
# Updates: https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.4-20241203.161809

# NeoForge: https://projects.neoforged.net/neoforged/neoforge
neo_version=21.4.3-beta
# Updates: https://projects.neoforged.net/neoforged/ModDevGradle
mdg_version=2.0.52-beta

# Fabric
# Updates: https://fabricmc.net/versions.html
fabric_loader_version=0.16.7

# Mod options
mod_name=FerriteCore
mod_author=malte0811
mod_id=ferritecore
mod_version=7.1.1

# TODO can this be made to work?
#org.gradle.configuration-cache=true
