plugins {
    id 'ferritecore.subproject-conventions'
    id 'net.neoforged.moddev' version "$mdg_version"
}

neoForge {
    neoFormVersion = neo_form_version
    addModdingDependenciesTo sourceSets.test
}

dependencies {
    compileOnly group: 'org.spongepowered', name: 'mixin', version: '0.8.5'
    compileOnly group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.5.0'
    implementation group: 'org.ow2.asm', name: 'asm-tree', version: '9.3'
    testImplementation(platform('org.junit:junit-bom:6.0.3'))
    testImplementation('org.junit.jupiter:junit-jupiter')
    testRuntimeOnly('org.junit.platform:junit-platform-launcher')
}

test {
    useJUnitPlatform()
}

processResources {
    def buildProps = project.properties.clone()

    filesMatching(['pack.mcmeta']) {
        expand buildProps
    }
}
