modLoader = "javafml"
loaderVersion = "[1,)"

license = "MIT"
[[mods]]
modId = "ferritecore"
version = "${file.jarVersion}"
displayName = "Ferrite Core"
authors = "malte0811"
description = '''
Reduces memory usage.
'''
logoFile = "logo.png"
[[dependencies.ferritecore]]
modId = "neoforge"
type = "required"
versionRange = "[21.0.0-beta,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.ferritecore]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.0,1.22)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config="ferritecore.predicates.mixin.json"
[[mixins]]
config="ferritecore.fastmap.mixin.json"
[[mixins]]
config="ferritecore.mrl.mixin.json"
[[mixins]]
config="ferritecore.dedupmultipart.mixin.json"
[[mixins]]
config="ferritecore.blockstatecache.mixin.json"
[[mixins]]
config="ferritecore.dedupbakedquad.mixin.json"
[[mixins]]
config="ferritecore.threaddetec.mixin.json"
[[mixins]]
config="ferritecore.modelsides.mixin.json"
[[mixins]]
config="ferritecore.accessors.mixin.json"
